services:
  postgres:
    image: postgres:16
    container_name: fluxocaixa-postgres-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - fluxocaixa-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: fluxocaixa-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - fluxocaixa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local
  rabbitmq_data_dev:
    driver: local

networks:
  fluxocaixa-network:
    driver: bridge