FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY *.sln ./
COPY src/ src/
COPY tests/ tests/

RUN dotnet restore

RUN dotnet build --no-restore

CMD ["dotnet", "test", "--no-build", "--verbosity", "normal"]